### ISSUE TITLE
lightning address check fails

### ISSUE THREAD

**Issue by f321x** [peakshift/makers.bolt.fun#169]
When trying to add my lightningaddress (x@lnaddress.com) to my profile i get "lightning address is invalid" but when opening 
https://lnaddress.com/.well-known/lnurlp/x i get status 200, so it should work, there is probably some bug.

**Comment by MTG2000** [comment]
Hey @f321x 
Thanks for reporting this.

I tried your lightning address just now, and it's as you said, not working.

The reason for that is actually simple.
When the user enters a lightning_address in the input field, I try to make a GET request to the URL of this lightning_address just to make sure that the user didn't mistype the URL.

But the reason why this request isn't working on the address that you mentioned is because the request is failing due to CORS policy.

So if the lnaddress server could return the CORS headers, then the problem should be solved.

**Comment by f321x** [comment]
Thx for the quick check. This should probably be changed in the Satdress Server then.
