### ISSUE TITLE
Create image upload service

### ISSUE THREAD

**Issue by johnsBeharry** [peakshift/makers.bolt.fun#51]
1. We need to have a service to handle the uploading of static image content.
2. Uploaded images need to be transformed. Some services also provide such functionality built-in to the same offering / API.
3. We currently use CloudFlare and Netlfiy, so it's preferred to use at little services as possible. Cloudflare currently offers an image store.
4. There are various resources that could include images (stories, comments, user profiles, projects, ...) they all should be using this image upload and retrieval service.

Potential Solutions
- https://www.cloudflare.com/products/cloudflare-images/
- AWS S3

**Comment by MTG2000** [comment]
Basically, there are 2 ways for building this service:

1- Handling the uploaded images on submission.
Which means that the users will select the images, and when he clicks "Submit" on whatever form he is on, the form data is sent together with the images selected.
pros: 
- simpler to develop  

cons: 
- long submission times
- not easy to display thumbnails and keeping the images in localStorage for saving local drafts for example.

2- Uploading the images on selection
Which means that images are immediately uploaded to the server after the user select them before he even clicks the 'Submit'.
So for example, there is an api route `/upload-images` that accepts images from any authenticated user, and stores them on some images hosting service, then returns the URLs of the hosted image to the client to display their thumbnails.
The backend should keep track of the uploaded images, so that if the user doesn't submit later a form that uses these images, then these images should be deleted from the hosting service.
(Maybe you run a cron job to check for stale images and delete them)

pros: 
- Much faster submission time
- user can immediately see how the images will look  

cons:
- a little bit more complex to develop

an examples for websites that uses the 2nd approach is Github, Gmail.

**Comment by MTG2000** [comment]
@Dolu89

How the images uploading service could probably work: 

There are many places in the app where a user can upload an image, & he might want to use his own images that are hosted on some external images hosting service.
What our images hosting needs to do primarily is to accept an image, then returns a permenant URL for it.

How do we handle the case where a user uploads an image for a post that he is writing, but then he don't publish it.
How will we find this "stale" image and remove it???

One solution could be this:
We will have a table in the DB called hosted-images for example.
this hosted-images DB can have the following fields:
link (primary key or we can use a normal primary-key), created_at, is_used

So when a user uploads an image:
1- We store it in the images hosting service.
2- We store the link & created_at in the DB
3- We return the link to the user.

Now if the user submits this object (eg.story) that he is working on, in the function that handles this submission, we can go over the used URLs, and check if any of the used images URLs are in the hosted-images table.
If so, we we mark this image as used.

So how will we detect unused images??
One way would be to run a scheduled job each X interval, and check for images that has a created_at older than Y amount (maybe 1 month for now), and that are not marked as used.
If we find such images, we first delete them from the images hosting service, then remove these entries from the DB.

Why are we marking the used images as is_used instead of removing them from the DB??
So that we can remove them if the user later update or delete his post & isn't using these images anymore.

So before the user delete/update his object, we can go over the images that were used in it, and check if they are hosted by looking them up in the hosted-images table.
If so, we delete them from the hosting service and delete their entries from the DB table.

**Comment by Dolu89** [comment]
> 

For the schema, I'll use this
```
  id        String   @id
  filename  String
  link      String
  createdAt DateTime @default(now())
  is_used   Boolean  @default(false)
```

id will be the unique file id from the hosting service and used as PK in your DB.
filename can be important if you want to use it in your UI (tooltips, or a list of uploaded files, etc)

**Comment by MTG2000** [comment]
Looks good to me.
Yeah, I forgot about the name, it'll sure come in handy

**Comment by johnsBeharry** [comment]
for accessibility -- we could also store a "description" or "caption" for alt tags? Can be autogenerated in the future via some image recognition api or set manually now in the editor.

**Comment by Dolu89** [comment]
@johnsBeharry @MTG2000 Can we have to list the different types of content who can include images?
Stories, Projects, etc.
So I can add foreign keys on the image table and link object to images

What do you think about having many nullable columns in the table HostedImage like
`story_id`, `project_id`, etc ?

**Comment by MTG2000** [comment]
I don't think it will just be `project_id` for example.
Because a single project can make use of images but in different fields.
Like `screenshots`, `thumbmail_image`, `cover_image`.
The same for story:
`cover_image`, `content_image`
etc.

So although we can add a new relation column for each type of `"<OBJECT>_<IMAGE_TYPE?_id"`, as you may have already guessed, this will quickly get messy.

Another solution that should scale better, is to just have 2 columns in the images table.
`item_id` & `item_type`

The `item_type` is a string that can have the format I mentioned above ( `"<OBJECT>_<IMAGE_TYPE?_id"` ).
While the `item_id` is the item's id 😅

You can see this kind of structure when you are building a notification system for example, where you also need to connect one table to only one field from many different tables.

**Comment by MTG2000** [comment]
Btw, you can see the usage of this method in our `Vote` modal.
A single vote entry can be given to many different modals (story, project, comment, ...etc)
So I used this same way for it.

**Comment by Dolu89** [comment]
I agree with your proposition. The only problem I think, can be a performance issue since you can't define a foreign key on item_id (because many other relation will use it), but it shouldn't be too bad on a small table like the image one.

To fix this problem, we should have created 1 image table per object type (story_image, project_image, etc...)

**Comment by MTG2000** [comment]
I don't think it will really be a problem.
Because most of the times we will be accessing the images from the other object table, not the other way around.
And the in the other object's table, the `image_id` is a foreign key.

**Comment by MTG2000** [comment]
Plus, as I mentioned earlier, I've seen it implemented this way in much bigger systems where the relation is used both ways, and it didn't really affect the performance.

Cause it's just that instead of the query being 
```
Select ... from 
Join ...
```

It becomes 2 simple `SELECT`s.
So it should be fine.

**Comment by Dolu89** [comment]
There will not be `image_id` in object's table. It's a 1->n relationship (1 story has many images, so it's `story_id` who will be stored in image's table)

But yeah, performance should be good anyway

**Comment by MTG2000** [comment]
> There will not be `image_id` in object's table. It's a 1->n relationship (1 story has many images, so it's `story_id` who will be stored in image's table)

Oh, yeah.
That's because we will be storing the image URLs directly in the object's table, right??

So in this case, I think that we will only need the relation in the images table so that if we want to delete this object at one point, we first check the images table to see if there are images with `item_type=<object.type>` & `item_id=<object.id>`, then delete them from the hosting service, and finally delete/update the object.

So actually in this case this table will be used even less frequently.

**Comment by Dolu89** [comment]
Call with @MTG2000 about storing images in DB

## Not retained solution
A solution could be to store a list of (cloudflare) IDs or (cloudflare) urls in the "object" table (project, story, etc) like it's already done with the `Project.screenshots` columns
The workflow should be this:

1. User start creating a new story.
2. User uploads some images. Images IDs are stored in `HostedImage` table and flagged as `is_used`=false
3. Scenario 1: User submit his story => Images IDs are stored in the story table like `Story.screenshots`, `Story.cover`, etc.
3.1. A the same time, images IDs used in the story are deleted from HostedImage table
4. Scenario 2: User cancel his story => Images have been uploaded on cloudflare
4.1. A scheduled job will remove these images with the flag `is_used`=false from `HostedImage` table and from cloudflare

This solution could works. But there is currently a problem if we change the hosting image provider in the future. (from cloudflare to amazon S3 or anything else)
Since stored IDs come from cloudflare, we can't use them with S3. 

So we though about a new nicer solution

## Solution
⚠ This solution will break what we have achieved today with the `HostedImage` table

### Changing the HostedImage schema to
```
id (internal id, not the hosting provider id anymore)
provider_image_id
provider (a relation with a provider table or a plain text like "cloudflare", "s3", "external", etc.)
url (used for "external" only?)
created_at
is_used
```

### Changing what is stored in our columns like `Project.screenshots`
Projects.screenshots = "{1, 2, 3}" => ids of HostedImage
User.avatar = 4

### A route that redirect our internal image ids to our current hosting provider
For example `https://makers.bolt.fun/image/1` HTTP 308 redirect to `https://imagedelivery.net/wyrwp3c-j0gDDUWgnE7lig/<provider_image_id>/public`


For old image uploaded by users, we can store it in HostedImage table like this
```
id: 5
provider_image_id: empty
provider: external
url: https://external_hosting_image.com/images/abc123
created_at: ...
is_used: true
```
and use the same route `https://makers.bolt.fun/image/5` to redirect to `https://external_hosting_image.com/images/abc123`

### Need to create a SQL migration script
to move all the old URL from `User.avatar`, `Project.screenshots`, etc. to the `HostedImage` table

### Chaning all the current queries 
to build images URL from IDs like `https://makers.bolt.fun/image/5`(serverside) to not break the frontend (since it currently use URLs)

Pros:
- Can be compatible with existing data
- Allows for hosting providers change
Cons:
- More works than expected
- Breaking change into the HostedImage schema

@johnsBeharry What's your opinion on it?

**Comment by MTG2000** [comment]
@Dolu89 

I've thinking more about this approach today, and I just realized that it really can affect the performance.

Yeah, in the cases where we are showing a page with only 2 images, it's not really big if we make an extra 2 queries on the `imgs` table & construct the proper URL before returning it.

But what about the cases where we are showing a page that has 50 images??
Like our main "Apps" page.

In this case, we will first make a DB query to select all the projects to show.
Then we either do 50 other `SELECT` or one `SELECT` with a left join that has a `WHERE` containing an array of 50 ids!!

And not just this page, many of the other website pages have a lot of content that have images (Category projects, feed, post details, ...etc)

And all of those will most of the times have at least 10 images together => meaning extra 10 queries for each user request.

I think that this will affect the performance not long from now.

Maybe we can introduce a caching service that can handle this, but this will bring its own set of new challenges and problems.

So personally, I think the 1st approach is much better in this regard.
Because it's much easier to implement, & definitely more performant.

The only downside for it was that it will require some work to be done if we later at some point decide to change our images hosting provider.

But even then, I think it's possible to write a manual script that fetches all the images in the different parts of our DB, re-uploads them to the new hosting, & update the old URLs with the new ones.
Won't be pretty & very easy, but doable.

@johnsBeharry 
How probable is it to change our images hosting service? 
And what are your thoughts on this?

**Comment by johnsBeharry** [comment]
> Redirect URL in the end is useless. We could also return the hosting image provider URL without any issue.

@Dolu89 I actually like the idea of using a url mapped to our domain. also could help with portability in the future if necessary. 

> How probable is it to change our images hosting service?

@MTG2000 Likelihood to change image hosts in the short term is unlikely for sometime but the opportunity would be there if https://github.com/synonymdev/slashtags does image hosting in their SlashDrive offering.

> But what about the cases where we are showing a page that has 50 images?? Like our main "Apps" page.

Won’t these be server to server calls anyway? The graphQL API would call to the image retrieval service to return the full response of images for the queried object. If so that’d be cheap and shouldn’t impact latency.
