### ISSUE TITLE
Show a basic list of stories on the profile page

### ISSUE THREAD

**Issue by johnsBeharry** [peakshift/makers.bolt.fun#69]
<img width="1196" alt="Screenshot 2022-07-11 at 13 37 52" src="https://user-images.githubusercontent.com/183140/178265903-d256140e-2bec-445d-acd0-f154fb412ed8.png">

**Comment by johnsBeharry** [comment]
@barefoot-88 a few points on this design

1. avatar, and username are redundant on the profile page as we do not currently support group posts, or anything else that would require us to show it on each list item.
2. I'm skeptical that vote count, and comment count are also relevant for this page also, individual post votes could be replaced with a tipping button on profile header for instance

**Comment by barefoot-88** [comment]
1. Agreed, this was included just because it was part of the standardised post component, however since it's on the user's page it can be taken off. That being said, if this was a story which tagged a product and was shown on the product's page, it could include this avatar + name.
2. Comments currently not available, so this can go for now. As for votes, I also agree could be hidden for the time being. Either that or we could have an aggregated vote counter at the top of the stories card, but maybe not super important atm.
3. I kind of agree, let's do it and hope it works.

<img width="1030" alt="Screenshot 2022-07-12 at 10 31 59" src="https://user-images.githubusercontent.com/36778205/178459182-32f165ff-558b-419d-a03a-71dd24904ec6.png">
